services:
  database:
    image: postgres
    restart: on-failure
    container_name: solid-backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: USERS
    ports:
      - "5433:5432"

