services:
  database:
    image: postgres
    restart: on-failure
    container_name: SpaceX-backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: THE-EMPLOYEES
    ports:
      - "5434:5432"

